server:
  port: 8083
spring:
  application:
    name: AGENDAMIENTO-APP
  datasource:
    url: jdbc:mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DBNAME}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

  config:
    import: optional:configserver:http://localhost:8085